DROP DATABASE Furniture
GO
CREATE DATABASE Furniture
GO
USE Furniture
GO
CREATE TABLE Users
(
	uid INT IDENTITY(1,1) PRIMARY KEY,
	username VARCHAR(150) NOT NULL UNIQUE,
	[password] VARCHAR(150) NOT NULL,
	fullname VARCHAR(150) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	address VARCHAR(150) NOT NULL,
	phonenumber VARCHAR(150) NOT NULL UNIQUE,
	avatarURL VARCHAR(MAX),
)

CREATE TABLE Categories
(
	cid INT IDENTITY(1, 1) PRIMARY KEY,
	cname VARCHAR(150) NOT NULL
)

CREATE TABLE Products
(
	pid INT IDENTITY(1, 1) PRIMARY KEY,
	pname VARCHAR(MAX) NOT NULL,
	price FLOAT NOT NULL,
	[pshortdesc] VARCHAR(MAX) NOT NULL,
	[pdesc] VARCHAR(MAX) NOT NULL,
	available BIT NOT NULL, 
)

CREATE TABLE Product_Categories
(
	pid INT FOREIGN KEY REFERENCES dbo.Products(pid),
	cid INT FOREIGN KEY REFERENCES dbo.Categories(cid),
	PRIMARY KEY(pid, cid)
)

CREATE TABLE Product_Images
(
	imgid INT PRIMARY KEY IDENTITY(1,1),
	pid INT FOREIGN KEY REFERENCES dbo.Products(pid),
	imageURL VARCHAR(MAX) NOT NULL,
)

CREATE TABLE Product_Comments 
(
	cmtid INT PRIMARY KEY IDENTITY(1,1),
	pid INT FOREIGN KEY REFERENCES dbo.Products(pid),
	uid INT FOREIGN KEY REFERENCES dbo.Users(uid),
	cdate DATETIME,
	comment VARCHAR(MAX) NOT NULL,
)

CREATE TABLE Contact 
(
	ctid INT IDENTITY(1,1) PRIMARY KEY,
	fullname VARCHAR(150) NOT NULL,
	email VARCHAR(150) NOT NULL,
	[subject] VARCHAR(150) NOT NULL,
	[message] VARCHAR(max) NOT NULL
)